.TH "AchSubscriber" 3 "15 Apr 2009" "Doxygen" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AchSubscriber \- The Subscriber Class is used for subscribing data of a circular shared memory buffer channel.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <achshm.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAchSubscriber\fP (const char *channel_name)"
.br
.ti -1c
.RI "ach_shm_error \fBopen\fP ()"
.br
.RI "\fIThis tries to create a link to the channel buffer. \fP"
.ti -1c
.RI "ach_shm_error \fBgetNext\fP (void *buffer, size_t *buffer_size, int *sequence)"
.br
.ti -1c
.RI "ach_shm_error \fBgetLatest\fP (void *buffer, size_t *buffer_size, int *index, int *sequence)"
.br
.ti -1c
.RI "void \fBsetFrequencyErrorCallBack\fP (void(*func)(void), int frequency)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBlast_time_read\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The Subscriber Class is used for subscribing data of a circular shared memory buffer channel. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AchSubscriber::AchSubscriber (const char * channel_name)"
.PP
This is used to create an instance of the subscriber class 
.PP
\fBParameters:\fP
.RS 4
\fIchannel_name\fP Input channel name to map. /dev/shm/channel_name.dat is mapped 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "ach_shm_error AchSubscriber::getNext (void * buffer, size_t * buffer_size, int * sequence)"
.PP
This is used to get the next buffer in the shared circular buffer memory. A counter is maintained in this class which decides the next buffer sequence to get 
.PP
\fBParameters:\fP
.RS 4
\fIbuffer\fP Input address to which buffer should be stored 
.br
\fIbuffer_size\fP Returns buffer_size written to buffer 
.br
\fIsequence\fP Returns sequence number of the current buffer 
.RE
.PP

.SS "ach_shm_error AchSubscriber::getLatest (void * buffer, size_t * buffer_size, int * index, int * sequence)"
.PP
This is used to get the latest stored buffer in the shared circular buffer memory 
.PP
\fBParameters:\fP
.RS 4
\fIbuffer\fP Input address to which buffer should be stored 
.br
\fIbuffer_size\fP Returns buffer_size written to buffer 
.br
\fIindex\fP Returns position of buffer in the circular buffer 
.br
\fIsequence\fP Returns sequence number of the current buffer 
.RE
.PP

.SS "void AchSubscriber::setFrequencyErrorCallBack (void(*)(void) func, int frequency)"
.PP
This function should be used sparingly.This will ensure real timeness of this instance of subscriber. After this function is registered, it is expected that there is a getNext or a getLatest call before every 1/frequency interval. Whenever this function is called and a function func is registered with a frequency. If a timer sees that a call is made later than 1/frequency interval it calls func. It is expected that the user will write an error handler in func to handle and out of frequency error. Needs further testing. While testing do not use usleep. 
.PP
\fBParameters:\fP
.RS 4
\fIfunc\fP Input pointer to error function handler 
.br
\fIfrequency\fP Input frequency 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen from the source code.
